name: nodejs
on:
  push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          check-latest: true
          node-version: lts/*
      - run: npm i
        working-directory: nodejs
      - run: npm test
        working-directory: nodejs
        env:
          GITHUB_TOKEN: ${{secrets.PAT}}